INSERT INTO products (id, name, category, price, description, image, gallery, available, catalog_single_preview, catalog_double_preview) VALUES
(1, 'Libro para Embarazo', 'libros', 1190, 'Cuaderno diseñado para acompañar y registrar cada etapa del embarazo. Tamaño A5, con 60 páginas en papel ecológico de 200 g, ideal para guardar ecografías, anotar controles médicos, pensamientos y recuerdos de esta etapa tan especial. Se entrega en bolsa de tela, perfecta para protegerlo y conservarlo con el tiempo.', '/pictures/libro_seguimiento_embarazo.jpeg', ARRAY['/pictures/libro_seguimiento_embarazo.jpeg', '/pictures/libroembarazo1.jpeg', '/pictures/libroembarazo2.jpeg', '/pictures/libroembarazo3.jpeg', '/pictures/libroembarazo4.jpeg', '/pictures/libroembarazo5.jpeg', '/pictures/libroembarazo6.jpeg', '/pictures/libroembarazo7.jpeg', '/pictures/libroembarazo8.jpeg', '/pictures/libroembarazo9.jpeg', '/pictures/libroembarazo10.jpeg'], true, false, false),
(2, 'Tarjetas del Primer Año', 'libros', 790, 'Set de 24 tarjetas ilustradas para los primeros doce meses y eventos clave; se presentan en bolsa de tela.', '/pictures/tarjetas1.jpeg', ARRAY['/pictures/tarjetas1.jpeg', '/pictures/tarjetas2.jpeg', '/pictures/tarjetas3.jpeg', '/pictures/tarjetas (1).jpeg', '/pictures/tarjetas (2).jpeg', '/pictures/tarjetas (3).jpeg', '/pictures/tarjetas (4).jpeg', '/pictures/tarjetas (5).jpeg', '/pictures/tarjetas (6).jpeg', '/pictures/tarjetas (7).jpeg', '/pictures/tarjetas (8).jpeg', '/pictures/tarjetas (9).jpeg', '/pictures/tarjetas (10).jpeg', '/pictures/tarjetas (11).jpeg'], true, false, false),
(3, 'Libro de Recuerdos del Bebé', 'libros', 1490, 'Libro diseñado para conservar los momentos más especiales del primer año de vida. Impreso en papel ecológico con 70 páginas de hojas gruesas de 200 g, ideales para escribir, pegar fotografías y guardar recuerdos. Incluye tarjeta personalizada con el nombre del bebé y se entrega en bolsa de lienzo para protegerlo y conservarlo.', '/pictures/libro_de_recuerdos_sin_personalizar.jpeg', ARRAY['/pictures/libro_de_recuerdos_sin_personalizar.jpeg', '/pictures/librorecuerdos1 (1).jpeg', '/pictures/librorecuerdos1 (2).jpeg', '/pictures/librorecuerdos1 (3).jpeg', '/pictures/librorecuerdos1 (4).jpeg', '/pictures/librorecuerdos1 (5).jpeg', '/pictures/librorecuerdos1 (6).jpeg', '/pictures/librorecuerdos1 (7).jpeg', '/pictures/librorecuerdos1 (8).jpeg'], true, false, false),
(4, 'Libro de Recuerdos Personalizado', 'libros', 1590, 'Versión personalizada del libro de recuerdos, con carátula diseñada con el nombre del bebé. Impreso en papel ecológico de 200 g, de excelente calidad. Incluye bolsa de lienzo para guardarlo y conservarlo.', '/pictures/libro_de_recuerdos_personalizado.jpeg', ARRAY['/pictures/libro_de_recuerdos_personalizado.jpeg', '/pictures/librorecuerdos1 (9).jpeg', '/pictures/librorecuerdos1 (10).jpeg', '/pictures/librorecuerdos1 (11).jpeg', '/pictures/librorecuerdos1 (12).jpeg', '/pictures/librorecuerdos1 (13).jpeg', '/pictures/librorecuerdos1 (14).jpeg', '/pictures/librorecuerdos1 (15).jpeg', '/pictures/librorecuerdos1 (16).jpeg', '/pictures/libro_personalizado (1).jpeg', '/pictures/libro_personalizado (2).jpeg'], true, false, false),
(5, 'MEMO Bajo del Mar', 'juegos', 590, 'Juego de memoria con ilustraciones de animales marinos. Cartas plastificadas y resistentes al agua, ideal para estimulación temprana.', '/pictures/memo1.jpeg', ARRAY['/pictures/memo1.jpeg', '/pictures/memo2.jpeg', '/pictures/memo (1).jpeg', '/pictures/memo (2).jpeg', '/pictures/memo (3).jpeg', '/pictures/memo (4).jpeg', '/pictures/memo (5).jpeg', '/pictures/memo (6).jpeg'], true, false, true),
(6, 'Almohadillas para Manos y Pies', 'accesorios', 390, 'Almohadillas diseñadas para tomar las huellas de las manos y los pies del bebé de forma simple y prolija, permitiendo conservar una impresión duradera de este momento único. Son ideales para completar la sección de huellas del Libro de Recuerdos del Bebé y guardar ese recuerdo especial para siempre.', '/pictures/almohadillas (1).jpeg', ARRAY['/pictures/almohadillas (1).jpeg', '/pictures/almohadillas (2).jpeg', '/pictures/almohadillas (3).jpeg', '/pictures/almohadillas (4).jpeg', '/pictures/almohadillas (5).jpeg', '/pictures/almohadillasproduct (1).jpeg', '/pictures/almohadillasproduct (2).jpeg'], true, false, false),
(7, 'Separadores de percha para ropa de bebé', 'ropa', 690, 'Organizá la ropita de tu bebé de forma práctica con nuestros separadores de perchas por edad. Son ideales para mantener el placard ordenado y encontrar fácilmente cada etapa, desde recién nacido hasta los primeros dos años. Elaborados con materiales resistentes y un diseño delicado, pensados para acompañar la estética de un espacio cálido, natural y cuidado.', '/pictures/separadoresropabebe (1).jpeg', ARRAY['/pictures/separadoresropabebe (1).jpeg', '/pictures/separadoresropabebe (2).jpeg', '/pictures/separadoresropabebe (3).jpeg', '/pictures/separadoresropabebe (4).jpeg', '/pictures/separadoresropabebe (5).jpeg'], true, false, false),
(8, 'Tarjetas Personalizadas Cumple', 'tarjetas', 370, 'Hacé que cada regalo tenga un toque único y especial. Estas tarjetas están diseñadas para acompañar tus obsequios de una forma delicada y significativa.Incluye 15 tarjetas personalizadas con el nombre que elijas Son ideales para cumpleaños infantiles, souvenirs o para sumar un detalle especial a tus regalos.', '/pictures/tarjetas_personalizadas_cumple (1).jpeg', ARRAY['/pictures/tarjetas_personalizadas_cumple (1).jpeg', '/pictures/tarjetas_personalizadas_cumple (2).jpeg', '/pictures/tarjetas_personalizadas_cumple (3).jpeg', '/pictures/tarjetas_personalizadas_cumple (4).jpeg', '/pictures/tarjetas_personalizadas_cumple (5).jpeg', '/pictures/tarjetas_personalizadas_cumple (6).jpeg'], true, false, false),
(9, 'Tarjetas Personalizadas para Evento', 'tarjetas', 400, 'Tarjetas personalizadas para eventos, un detalle delicado y único para acompañar tus celebraciones. Ideales para cumpleaños, nacimientos, comunión y más, se personalizan con nombre y datos del evento. Incluyen bolsita de tela. Precio $20 por unidad, mínimo 20 unidades. Un recuerdo simple, lindo y pensado con dedicación.', '/pictures/TARJETAS_PERSONALIZADAS_EVENTO (1).jpeg', ARRAY['/pictures/TARJETAS_PERSONALIZADAS_EVENTO (1).jpeg', '/pictures/TARJETAS_PERSONALIZADAS_EVENTO (2).jpeg', '/pictures/TARJETAS_PERSONALIZADAS_EVENTO (3).jpeg', '/pictures/TARJETAS_PERSONALIZADAS_EVENTO (4).jpeg'], true, false, false),
(10, 'Frascos de Recuerdos para Bebé', 'accesorios', 390, 'Pequeños tesoros para guardar el primer diente, el primer pelito y el cordón umbilical. Fabricados en madera natural, con un diseño delicado para conservar los recuerdos más valiosos de tu bebé.', '/pictures/frascos_de_recuerdos_para_bebe (1).jpeg', ARRAY['/pictures/frascos_de_recuerdos_para_bebe (1).jpeg', '/pictures/frascos_de_recuerdos_para_bebe (2).jpeg', '/pictures/frascos_de_recuerdos_para_bebe (3).jpeg', '/pictures/frascos_de_recuerdos_para_bebe (4).jpeg', '/pictures/frascos_de_recuerdos_para_bebe (5).jpeg'], true, false, false),
(11, 'MEMO en el Bosque', 'juegos', 590, 'Juego de memoria con ilustraciones de animales y elementos del bosque. Cartas plastificadas y resistentes al agua, ideal para estimulación temprana.', '/pictures/memobosque (1).jpeg', ARRAY['/pictures/memobosque (1).jpeg', '/pictures/memobosque (2).jpeg', '/pictures/memobosque (3).jpeg', '/pictures/memobosque (4).jpeg', '/pictures/memobosque (5).jpeg'], true, false, true)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));
